repos:
  - repo: local
    hooks:
      - id: format-and-lint
        name: Format and Lint
        entry: python format_and_lint.py
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        verbose: true