apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hypercode-core
  namespace: hypercode
spec:
  rules:
    - host: hypercode.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hypercode-core
                port:
                  number: 80
