apiVersion: v1
kind: Service
metadata:
  name: hypercode-core
  namespace: hypercode
spec:
  selector:
    app: hypercode-core
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
